export const chatData: object = {
  'Tech Ninjas': {
    profileImg: 'profile_picture.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'you',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'johm',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'you',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'abc',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last meaage 1',
        name: 'akasas',
        time: '9:05AM',
        color: '#ebc634',
      },
    ],
  },
  'Don’t join': {
    profileImg: 'chatareaprofile.png',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: ' extra texts how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz extra texts',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some extra texts text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 2',
        name: 'amal1',
        time: '9:00AM',
        color: '#ebc634',
      },
    ],
  },
  'Life for friends': {
    profileImg: 'one.jpg',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey extra texts guyz',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text extra texts 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 3',
        name: 'amal1',
        time: '9:15AM',
        color: '#ebc634',
      },
    ],
  },
  'The Untouchables': {
    profileImg: 'two.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how extra texts you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last extra texts message 4',
        name: 'amal1',
        time: '10:40AM',
        color: '#ebc634',
      },
    ],
  },
  'Life and Music': {
    profileImg: 'chatareaprofile.png',
    muted: false,
    chats: [
      {
        message: 'hi extra texts',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey extra texts guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last extra texts message 5',
        name: 'amal1',
        time: '10:00AM',
        color: '#ebc634',
      },
    ],
  },
  'The Walkie Talkie': {
    profileImg: 'three.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'extra texts how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text extra texts 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'extra texts last message 6',
        name: 'amal1',
        time: '9:40AM',
        color: '#ebc634',
      },
    ],
  },
  'People of my life': {
    profileImg: 'one.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 7',
        name: 'amal1',
        time: '9:30AM',
        color: '#ebc634',
      },
    ],
  },
  'Country’s future weapons': {
    profileImg: 'three.jpg',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 8',
        name: 'amal1',
        time: '9:00AM',
        color: '#ebc634',
      },
    ],
  },
  keys: [
    'Tech Ninjas',
    'Don’t join',
    'Life for friends',
    'The Untouchables',
    'Life and Music',
    'The Walkie Talkie',
    'People of my life',
    'Country’s future weapons',
  ],
};
