export const chatData: object = {
  user1: {
    profileImg: 'profile_picture.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'you',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'johm',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'you',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'abc',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last meaage 1',
        name: 'akasas',
        time: '9:05AM',
        color: '#ebc634',
      },
    ],
  },
  user2: {
    profileImg: 'chatareaprofile.png',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 2',
        name: 'amal1',
        time: '9:00AM',
        color: '#ebc634',
      },
    ],
  },
  user3: {
    profileImg: 'one.jpg',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 3',
        name: 'amal1',
        time: '9:15AM',
        color: '#ebc634',
      },
    ],
  },
  user4: {
    profileImg: 'two.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'you',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 4',
        name: 'amal1',
        time: '10:40AM',
        color: '#ebc634',
      },
    ],
  },
  user5: {
    profileImg: 'chatareaprofile.png',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 5',
        name: 'amal1',
        time: '10:00AM',
        color: '#ebc634',
      },
    ],
  },
  user6: {
    profileImg: 'three.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 6',
        name: 'amal1',
        time: '9:40AM',
        color: '#ebc634',
      },
    ],
  },
  user7: {
    profileImg: 'one.jpg',
    muted: true,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 7',
        name: 'amal1',
        time: '9:30AM',
        color: '#ebc634',
      },
    ],
  },
  user8: {
    profileImg: 'three.jpg',
    muted: false,
    chats: [
      {
        message: 'hi',
        name: 'abhi',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'how you',
        name: 'john1',
        time: '9:27AM',
        color: '#ebc634',
      },
      {
        message: 'hey guyz',
        name: 'max1',
        time: '9:29AM',
        color: '#34ebe2',
      },
      {
        message: 'some text 1',
        name: 'arun1',
        time: '9:25AM',
        color: '#eb344f',
      },
      {
        message: 'some text 1',
        name: 'aahi1',
        time: '9:25AM',
        color: '#34eb8c',
      },
      {
        message: 'last message 8',
        name: 'amal1',
        time: '9:00AM',
        color: '#ebc634',
      },
    ],
  },
  keys: [
    'user1',
    'user2',
    'user3',
    'user4',
    'user5',
    'user6',
    'user7',
    'user8',
  ],
};
